name: Build

on:
  push:
    branches:
      - nixos-unstable
  repository_dispatch:

jobs:
  build_nixos_unstable:
    name: Build (nixos-unstable)
    if: github.event_name != 'repository_dispatch' || github.event.client_payload.channel == 'nixos-unstable'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@565940cd14fa3685adb83359327b06de3e999f30
      with:
        name: kwin-lowlatency
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        pushFilter: '^nixexprs.tar.xz$'
    - run: nix-build build.nix

  build_nixos_unstable_small:
    name: Build (nixos-unstable-small)
    if: github.event_name != 'repository_dispatch' || github.event.client_payload.channel == 'nixos-unstable-small'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable-small
    - uses: cachix/cachix-action@565940cd14fa3685adb83359327b06de3e999f30
      with:
        name: kwin-lowlatency
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        pushFilter: '^nixexprs.tar.xz$'
    - run: nix-build build.nix
