name: Build

on:
  push:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable-small
    - uses: cachix/cachix-action@v8
      with:
        name: kwin-lowlatency
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build build.nix
