name: Build on push

on: push

jobs:
  build_nixos_unstable:
    name: Dispatch build (nixos-unstable)
    if: github.ref == 'refs/heads/nixos-unstable'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: 'Build: nixos-unstable (push)'
          client-payload: '{"channel": "nixos-unstable"}'
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: 'Build: nixos-unstable-small (push)'
          client-payload: '{"channel": "nixos-unstable-small"}'
