name: Build on push

on: push

jobs:
  build_nixos_unstable:
    name: Dispatch build (nixos-unstable)
    if: github.ref == 'refs/heads/nixos-unstable'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [nixos-unstable, nixos-unstable-small]
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: 'Build: ${{ matrix.channel }} (push)'
          client-payload: '{"channel": "${{ matrix.channel }}"}'
