name: Build

on: repository_dispatch

jobs:
  build:
    name: Build (${{ github.event.client_payload.channel }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:${{ github.event.client_payload.channel }}
    - uses: cachix/cachix-action@565940cd14fa3685adb83359327b06de3e999f30
      with:
        name: kwin-lowlatency
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        pushFilter: '^nixexprs.tar.xz$'
    - run: nix-build build.nix
