name: Build

on:
  push:
  repository_dispatch:

jobs:
  build:
    name: Build (${{ matrix.channel }})
    runs-on: ubuntu-latest

    # Build for a single channel if triggered by a repository_dispatch event,
    # otherwise build for all channels.
    # TODO: This is a bit of a hack and does not scale well.
    strategy:
      matrix:
        channel: [nixos-unstable, nixos-unstable-small]
        dispatch_channel:
          - ${{ github.event.client_payload.channel }}
        exclude:
          - channel: nixos-unstable
            dispatch_channel: nixos-unstable-small
          - channel: nixos-unstable-small
            dispatch_channel: nixos-unstable

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:${{ matrix.channel }}
    - uses: cachix/cachix-action@v8
      with:
        name: kwin-lowlatency
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix-build build.nix
