name: Build

on:
  push:
  repository_dispatch:

jobs:
  build:
    name: Build (${{ matrix.channel }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: [nixos-unstable, nixos-unstable-small]
        skip:
          - ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.channel != matrix.channel }}
        exclude:
          - channel: nixos-unstable
            skip: true
          - channel: nixos-unstable-small
            skip: true

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:${{ matrix.channel }}
    - uses: cachix/cachix-action@v8
      with:
        name: kwin-lowlatency
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix-build build.nix
